docker:
  image: yegor256/java8
assets:
  settings.xml: yegor256/home#assets/takes/settings.xml
  pubring.gpg: yegor256/home#assets/pubring.gpg
  secring.gpg: yegor256/home#assets/secring.gpg
env:
  MAVEN_OPTS: -XX:MaxPermSize=256m -Xmx1g
  JAVA_OPTS: -XX:MaxPermSize=256m -Xmx1g
install: |
  sudo gem install --no-rdoc --no-ri pdd
  sudo gem install --no-rdoc --no-ri xcop
merge:
  script: |
    pdd -f /dev/null
    mvn clean install -Pqulice --errors --settings ../settings.xml
deploy:
  script: |
    echo There is nothing to deploy
    exit 1
release:
  script: |-
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Psonatype -Pqulice --errors --settings ../settings.xml
